@startuml
'skinparam backgroundColor transparent
skinparam linetype ortho // orthogonal lines for cleaner routing

[PackageResolver] as resolver
[PackageProvider] as provider
[PackageApplier] as applier
() "Your application\n(old version)" as old
() "Your application\n(new version)" as new

old --> resolver : "packages\nsource\nURL / path"
resolver ...> old : "available\npackages\nwith\nURLs / paths"
old -right-> provider : "package URL / path"
provider -right-> applier : "local package file"
applier --> new : "restart\napplication"

@enduml
