@startuml
skinparam backgroundColor transparent
'skinparam linetype ortho // orthogonal lines for cleaner routing

package "Upme" {
    [PackageResolver] as resolver
    [PackageProvider\n(downloads the update package)] as provider
    [PackageApplier\n(applies the update package)] as applier
}
node "Your application \n(outdated)" as old_app #dd5555
node "Your application \n(new version)" as new_app #55dd55

old_app -left-> resolver : "1. pass update server\nURL and current\napplication version"
resolver .down.> old_app : "return newer available\nversions and their\ndownload URLs"
old_app -up-> provider : "2. specify desired\nversion"
provider -right-> applier : "path to the \ndownloaded file"
applier -down-> new_app : "restart"

@enduml
