name: linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for deploying the coverage badge

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'maven'

      - name: Build, execute unit tests, package, execute integration tests
        run: mvn --batch-mode verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Code Coverage Badge
        if: always()
        uses: cicirello/jacoco-badge-generator@v2.12.0
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: target/site/jacoco/badges

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: always()
        with:
          folder: target/site/jacoco
